config/routes.rb
  mount WillFilter::Engine => "/will_filter"

  resources :attaches,:except=>[:show] do 
  end

  resources :klassplanitems do 
    member do 
      post 'set_finished'
    end
  end

  get 'entrance/:id/finish_baoming_kpi'=>"entrance#finish_baoming_kpi",:as=>"entrance_finish_baoming_kpi"
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  get "entrance/resources"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"

  post "api/login"

  post "api/logout"

  post "api/notifications"

  post "api/notification"

  post "api/notificate"  

  post 'api/feedback'

  resources :markets do 
    resources :clients do
    end
  end

  resources :students do 
    resources :achieves do
      member do
        match :finish
        match :unfinish
      end
    end
  end

  resources :baomings_klassplanitems do
    member do
      match :plan
      match :wait_confirm
      match :confirm
      match :request_leave
      match :leave
      match :finish
      match :uncomplete
    end
  end
  resources :projects do

    resources :achieves

    resources :feedbacks

    resources :stats

    resources :entrance do
      collection do
        match 'index'
        match 'feedbacks'
      end
    end

    resources :notification_templates

    resources :seasons do 
      member do
        match :set_now
      end
    end

    

    resources :rules

    resources :baomings,:except=>[:new,:create] do
      member do
        match :pay
      end
    end

  	resources :markets

    resources :courses

    resources :services

  	resources :rooms do
      collection do
        match 'filter_rooms'
      end
      member do
        match 'duplicate'
      end
    end

  	resources :teachers do
      member do
        match 'duplicate'
      end
    end

  	resources :students do
      member do
        match 'duplicate'
        match 'to_client'
        match 'to_student'
        match 'to_alumna'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :clients do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :alumnas do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :notifications do
      member do 
        match 'confirm'
        match 'unconfirm'
      end
    end

    resources :klassplans do
      member do 
        match 'start_plan'
        match 'confirm_plan'
        match 'ajax_menu'
        match 'ajax_kpis'
        match 'ajax_teachers'
        match 'ajax_rooms'
        match 'ajax_resources'
        match 'ajax_baoming'
        match 'wait_teacher_confirm'
      end

      collection do
        match 'planed_calendar'
        match 'planing_calendar'
        match 'autoplaning_calendar'
        match 'finished_calendar'
        match 'all_calendar'
        match 'auto'
        match 'start_auto'
        match 'dashborad'
      end
    end

    resources :reviews do
      member do
        match 'start'
        match 'set_feedbacked'
      end
      collection do
        get 'all'
        get 'my'
        get 'my_finished'
        get 'my_unfinished'
        get 'my_payed'
        match 'search_by_phone'
        match 'chose_reviewers'
        match 'available_reviewers'
      end
    end
  end

  resources :services

  resources :scores

  resources :warnings

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'

app/controllers/achieves_controller.rb
# encoding: utf-8
class AchievesController < ApplicationController
  # GET /achieves
  # GET /achieves.json
  Achiefe
  before_filter :find_project,:find_person

  def finish
    @achiefe = Achiefe.find(params[:id])
    @achiefe.finish
    redirect_to request.referer
  end

  def unfinish
    @achiefe = Achiefe.find(params[:id])
    @achiefe.unfinish
    redirect_to request.referer
  end

  def index
    @achieves = Achiefe.order('created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @achieves }
    end
  end

  # GET /achieves/1
  # GET /achieves/1.json
  def show
    @achiefe = Achiefe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @achiefe }
    end
  end

  # GET /achieves/new
  # GET /achieves/new.json
  def new
    @achiefe = Achiefe.new
    @achiefe.person = @person if @person

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @achiefe }
    end
  end

  # GET /achieves/1/edit
  def edit
    @achiefe = Achiefe.find(params[:id])
  end

  # POST /achieves
  # POST /achieves.json
  def create
    @achiefe = Achiefe.new(params[:achiefe])

    respond_to do |format|
      if @achiefe.save
        @person = @achiefe.person
        if @person.client?
          format.html { redirect_to project_client_path(@project,@person), notice: '成就创建成功' }
        end
        if @person.student?
          format.html { redirect_to project_student_path(@project,@person), notice: '成就创建成功' }
        end
        if @person.alumna?
          format.html { redirect_to project_alumna_path(@project,@person), notice: '成就创建成功' }
        end
      else
        format.html { render action: "new" }
        format.json { render json: @achiefe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /achieves/1
  # PUT /achieves/1.json
  def update
    @achiefe = Achiefe.find(params[:id])

    respond_to do |format|
      if @achiefe.update_attributes(params[:achiefe])
        format.html { redirect_to @achiefe, notice: 'Achiefe was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @achiefe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /achieves/1
  # DELETE /achieves/1.json
  def destroy
    @achiefe = Achiefe.find(params[:id])
    @achiefe.destroy

    respond_to do |format|
      format.html { redirect_to achieves_url }
      format.json { head :no_content }
    end
  end

  private 

  def find_project
    # p params
    @project = Project.find_by_identifier(params[:project_id])
    # p @project
  end          

  def find_person
    # p params
    @person = Person.find_by_id(params[:person_id])
    p '.'*10
    p @person
    # p @project
  end            
end

app/helpers/achieves_helper.rb
module AchievesHelper
end

app/views/achieves/_form.html.erb
<%=render 'common/css'%>
<%
  if @achiefe.new_record?
    @url = project_achieves_path(@project)
  else
    @url = project_achiefe_path(@project,@achiefe)
  end
%>

<%= simple_form_for @achiefe,:url=>@url, :html => { :class => 'form-horizontal' } do |f| %>
  <%= error_messages_for 'achiefe' %>
  <%= f.input :title %>
  <%= f.input :person_id ,:collection=>@project.students,:label_method=>:username%>
<!-- 
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :job %><br />
    <%= f.text_area :job %>
  </div> -->
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn' %>
  </div>
<% end %>

app/views/achieves/_list.html.erb
<%- model_class = Achiefe -%>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
<!--       <th>公司</th>
      <th>职位</th>
      <th>工作内容</th>
      <th>开始时间</th>
      <th>结束时间</th> -->
      <th>成就内容</th>
      <th>成就状态</th>
      <th>创建时间</th>
      <th>操作</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |item| %>
    <tr>
      <th><%=item.title%></th>
      <th><%=t item.state%></th>
      <th><%=item.created_at%></th>
      <th>
        <%=link_to '完成',finish_student_achiefe_path(item.person,item) unless item.finished? %>
        <%=link_to '未完成',unfinish_student_achiefe_path(item.person,item) unless item.unfinished? %>
      </th>
<!--       <th><%=item.company%></th>
      <th><%=item.position%></th>
      <th><%=item.job%></th>
      <th><%=item.started_at%></th>
      <th><%=item.ended_at%></th> -->
    </tr>
    <% end %>
  </tbody>
</table>

app/views/achieves/edit.html.erb
<h1>Editing achiefe</h1>

<%= render 'form' %>

app/views/achieves/index.html.erb
<h1>Listing achieves</h1>

<table>
  <tr>
    <th>Company</th>
    <th>Position</th>
    <th>Duration</th>
    <th>Job</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @achieves.each do |achiefe| %>
  <tr>
    <td><%= achiefe.company %></td>
    <td><%= achiefe.position %></td>
    <td><%= achiefe.duration %></td>
    <td><%= achiefe.job %></td>
    <td><%= link_to 'Show', achiefe %></td>
    <td><%= link_to 'Edit', edit_achiefe_path(achiefe) %></td>
    <td><%= link_to 'Destroy', achiefe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Achiefe', new_achiefe_path %>

app/views/achieves/new.html.erb
<h1>创建成就</h1>

<%= render 'form' %>

app/views/achieves/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_achiefe_path(@achiefe) %> |
<%= link_to 'Back', achieves_path %>
<p>
  <b>Company:</b>
  <%= @achiefe.company %>
</p>

<p>
  <b>Position:</b>
  <%= @achiefe.position %>
</p>

<p>
  <b>Duration:</b>
  <%= @achiefe.duration %>
</p>

<p>
  <b>Job:</b>
  <%= @achiefe.job %>
</p>