config/routes.rb
  mount WillFilter::Engine => "/will_filter"

  resources :attaches,:except=>[:show] do 
  end

  resources :klassplanitems do 
    member do 
      post 'set_finished'
    end
  end

  get 'entrance/:id/finish_baoming_kpi'=>"entrance#finish_baoming_kpi",:as=>"entrance_finish_baoming_kpi"
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  get "entrance/resources"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"

  post "api/login"

  post "api/logout"

  post "api/notifications"

  post "api/notification"

  post "api/notificate"  

  post 'api/feedback'

  resources :markets do 
    resources :clients do
    end
  end

  resources :students do 
    resources :achieves do
      member do
        match :finish
        match :unfinish
      end
    end
  end

  resources :baomings_klassplanitems do
    member do
      match :plan
      match :wait_confirm
      match :confirm
      match :request_leave
      match :leave
      match :finish
      match :uncomplete
    end
  end
  resources :projects do

    resources :achieves

    resources :feedbacks

    resources :stats

    resources :entrance do
      collection do
        match 'index'
        match 'feedbacks'
      end
    end

    resources :notification_templates

    resources :seasons do 
      member do
        match :set_now
      end
    end

    

    resources :rules

    resources :baomings,:except=>[:new,:create] do
      member do
        match :pay
      end
    end

  	resources :markets

    resources :courses

    resources :services

  	resources :rooms do
      collection do
        match 'filter_rooms'
      end
      member do
        match 'duplicate'
      end
    end

  	resources :teachers do
      member do
        match 'duplicate'
      end
    end

  	resources :students do
      member do
        match 'duplicate'
        match 'to_client'
        match 'to_student'
        match 'to_alumna'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :clients do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :alumnas do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :notifications do
      member do 
        match 'confirm'
        match 'unconfirm'
      end
    end

    resources :klassplans do
      member do 
        match 'start_plan'
        match 'confirm_plan'
        match 'ajax_menu'
        match 'ajax_kpis'
        match 'ajax_teachers'
        match 'ajax_rooms'
        match 'ajax_resources'
        match 'ajax_baoming'
        match 'wait_teacher_confirm'
      end

      collection do
        match 'planed_calendar'
        match 'planing_calendar'
        match 'autoplaning_calendar'
        match 'finished_calendar'
        match 'all_calendar'
        match 'auto'
        match 'start_auto'
        match 'dashborad'
      end
    end

    resources :reviews do
      member do
        match 'start'
        match 'set_feedbacked'
      end
      collection do
        get 'all'
        get 'my'
        get 'my_finished'
        get 'my_unfinished'
        get 'my_payed'
        match 'search_by_phone'
        match 'chose_reviewers'
        match 'available_reviewers'
      end
    end
  end

  resources :services

  resources :scores

  resources :warnings

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'

app/models/score.rb
class Score < ActiveRecord::Base
  attr_accessible :student_id, :type, :value,:title
  belongs_to :student
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.order('created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scores }
    end
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
    @score = Score.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/new
  # GET /scores/new.json
  def new
    @score = Score.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @score }
    end
  end

  # GET /scores/1/edit
  def edit
    @score = Score.find(params[:id])
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(params[:score])

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render json: @score, status: :created, location: @score }
      else
        format.html { render action: "new" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scores/1
  # PUT /scores/1.json
  def update
    @score = Score.find(params[:id])

    respond_to do |format|
      if @score.update_attributes(params[:score])
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score = Score.find(params[:id])
    @score.destroy

    respond_to do |format|
      format.html { redirect_to scores_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/scores/_form.html.erb
<%= form_for @score, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :value, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :value, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :person_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :person_id, Person.all, :id, :username %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn ' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                scores_path, :class => 'btn' %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<%- model_class = Score -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scores/index.html.erb
<%- model_class = Score -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:value) %></th>
      <th><%= model_class.human_attribute_name(:state) %></th>
      <th><%= model_class.human_attribute_name(:person_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= link_to score.value, score_path(score) %></td>
        <td><%= score.state %></td>
        <td><%= score.person_id %></td>
        <td><%= score.created_at.to_formatted_s(:db) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_score_path(score), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      score_path(score),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_score_path,
            :class => 'btn ' %>

app/views/scores/new.html.erb
<%- model_class = Score -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/scores/show.html.erb
<%- model_class = Score -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>
<div class="row">
  <div class="pull-right">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              scores_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_score_path(@score), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              score_path(@score),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
  </div>
</div>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @score.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
  <dd><%= @score.state %></dd>
  <dt><strong><%= model_class.human_attribute_name(:person_id) %>:</strong></dt>
  <dd><%= @score.person_id %></dd>
</dl>