config/routes.rb
  mount WillFilter::Engine => "/will_filter"

  resources :attaches,:except=>[:show] do 
  end

  resources :klassplanitems do 
    member do 
      post 'set_finished'
    end
  end

  get 'entrance/:id/finish_baoming_kpi'=>"entrance#finish_baoming_kpi",:as=>"entrance_finish_baoming_kpi"
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  get "entrance/resources"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"

  post "api/login"

  post "api/logout"

  post "api/notifications"

  post "api/notification"

  post "api/notificate"  

  post 'api/feedback'

  resources :markets do 
    resources :clients do
    end
  end

  resources :students do 
    resources :achieves do
      member do
        match :finish
        match :unfinish
      end
    end
  end

  resources :baomings_klassplanitems do
    member do
      match :plan
      match :wait_confirm
      match :confirm
      match :request_leave
      match :leave
      match :finish
      match :uncomplete
    end
  end
  resources :projects do

    resources :achieves

    resources :feedbacks

    resources :stats

    resources :entrance do
      collection do
        match 'index'
        match 'feedbacks'
      end
    end

    resources :notification_templates

    resources :seasons do 
      member do
        match :set_now
      end
    end

    

    resources :rules

    resources :baomings,:except=>[:new,:create] do
      member do
        match :pay
      end
    end

  	resources :markets

    resources :courses

    resources :services

  	resources :rooms do
      collection do
        match 'filter_rooms'
      end
      member do
        match 'duplicate'
      end
    end

  	resources :teachers do
      member do
        match 'duplicate'
      end
    end

  	resources :students do
      member do
        match 'duplicate'
        match 'to_client'
        match 'to_student'
        match 'to_alumna'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :clients do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :alumnas do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :notifications do
      member do 
        match 'confirm'
        match 'unconfirm'
      end
    end

    resources :klassplans do
      member do 
        match 'start_plan'
        match 'confirm_plan'
        match 'ajax_menu'
        match 'ajax_kpis'
        match 'ajax_teachers'
        match 'ajax_rooms'
        match 'ajax_resources'
        match 'ajax_baoming'
        match 'wait_teacher_confirm'
      end

      collection do
        match 'planed_calendar'
        match 'planing_calendar'
        match 'autoplaning_calendar'
        match 'finished_calendar'
        match 'all_calendar'
        match 'auto'
        match 'start_auto'
        match 'dashborad'
      end
    end

    resources :reviews do
      member do
        match 'start'
        match 'set_feedbacked'
      end
      collection do
        get 'all'
        get 'my'
        get 'my_finished'
        get 'my_unfinished'
        get 'my_payed'
        match 'search_by_phone'
        match 'chose_reviewers'
        match 'available_reviewers'
      end
    end
  end

  resources :services

  resources :scores

  resources :warnings

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'

app/models/notification.rb
# encoding: utf-8
class Notification < ActiveRecord::Base
  # paginates_per 10
  attr_accessible :required,:content, :notificatable_id, :notificatable_type, :state, :title,:notify_at,:notificatable,:person,:person_id
  
  belongs_to :notificatable,:polymorphic=>true

  belongs_to :person

  before_validation do |record|
    record.state = 'normal' if record.state == '无需确认通知'
    record.state = 'confirm' if record.state == '需确认通知'
  end

  before_create :set_notify_at

  # 创建待老师确认的通知 ，notificate is klassplan
  def self.create_teacher_confirm(notificatable)
    n = Notification.new
    n.state = 'teacher_confirm'
    n.notificatable = notificatable
    n.person = notificatable.teacher
    n.title = n.notification_title
    n.content = n.notification_content
    # p n.title
    n.save
  end

  # 创建待学生确认的通知 ，notificate is baoming
  def self.create_student_confirm(notificatable,student)
    n = Notification.new
    n.state = 'student_confirm'
    n.notificatable = notificatable
    n.person = student
    n.title = n.notification_title
    n.content = n.notification_content
    n.valid?
    n.save
  end

  # 设置通知时间
  def set_notify_at
    self.notify_at = Time.zone.now if self.notify_at.blank?
  end


  def handle_response response
    if response == 'confirm'
      self.confirm
    else
      self.unconfirm
    end
  end

  # 根据notificatable 获得 通知标题
  def notification_title
  	case state 
    when 'teacher_confirm'
			notificatable.teacher_confirm_title
    # when 'student_confirm'
    #   notificatable.student_confirm_title      
    else
      notificatable.confirm_title
		end
	end

  # 根据notificatable 获得 通知内容
	def notification_content
		case state 
    when 'teacher_confirm'
			notificatable.teacher_confirm_content
		# when 'student_confirm'
		# 	notificatable.student_confirm_content
    else 
      notificatable.confirm_content
		end
	end

  # 确认通知
	def confirm
    if notificatable
      case self.state 
      when 'teacher_confirm'
        notificatable.wait_student_confirm 
      # when 'student_confirm'
      #   notificatable.wait_student_confirm 
      else
        notificatable.confirm
      end
    end
    
		self.response = :confirm
		self.save
	end		

  # 通知来源 ， 服务器还是客户端
  def laiyuan
    if response == nil
      ''
    elsif is_server
      '服务器'
    else
      '客户端'
    end
  end

	def unconfirm
    begin
		  notificatable.unconfirm if notificatable 
    rescue
    end
		self.response = :unconfirm
		self.save
	end

  def clear_confirm
    self.response = nil
    self.save
  end		

  state_machine :state do 
    state :normal do
      def state_zh
        '无需确认通知'
      end
    end

    state :confirm do
      def state_zh
        '需确认通知'
      end
    end

  	state :teacher_confirm do
      def state_zh
        '教师确认通知'
      end
  	end

  	state :student_confirm do
      def state_zh
        '学员确认通知'
      end
  	end
  end 
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
	Notification
  before_filter :find_project,:authorize
  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.page(params[:page]).order('created_at desc')
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notifications }
    end
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def confirm
    notification = Notification.find(params[:id])
    notification.confirm
    notification.is_server = true
    notification.save
    redirect_to request.referer
  end

  def unconfirm
    notification = Notification.find(params[:id])
    notification.unconfirm
    notification.is_server = true
    notification.save
    redirect_to request.referer
  end


  # GET /notifications/1
  # GET /notifications/1.json
  def show
    @notification = Notification.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/new
  # GET /notifications/new.json
  def new
    begin
      gon.students_id = params[:students_id].split('-').map{|i|i.to_i}
    rescue
      gon.students_id = []
    end
    @notification = Notification.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification }
    end
  end

  # GET /notifications/1/edit
  def edit
    @notification = Notification.find(params[:id])
  end

  # POST /notifications
  # POST /notifications.json
  def create
    params[:notification]['person_id'].each do |id|
      person = Person.find_by_id(id)
      if person
        @notification = Notification.new(params[:notification])
        @notification.person = person
        @notification.save
      end
    end
    redirect_to project_notifications_path(@project)
  end

  # PUT /notifications/1
  # PUT /notifications/1.json
  def update
    @notification = Notification.find(params[:id])

    respond_to do |format|
      if @notification.update_attributes(params[:notification])
        format.html { redirect_to project_notification_path(@project,@notification), notice: 'Notification was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification = Notification.find(params[:id])
    @notification.destroy

    respond_to do |format|
      format.html { redirect_to project_notifications_url(@project) }
      format.json { head :no_content }
    end
  end
  private 

  def find_project
    # p params
    @project = Project.find_by_identifier(params[:project_id])
    # p @project
  end          
end

app/helpers/notifications_helper.rb
# encoding: utf-8
module NotificationsHelper
	def response_msg notification
		unless notification.normal?
			msg = ''
			msg = msg + t(notification.response) if notification.response 
	    msg = msg + link_to('同意',confirm_project_notification_path(@project,notification),:class=>'btn btn-mini') unless notification.response
	    msg = msg + ' '  
	    msg = msg + link_to('不同意',unconfirm_project_notification_path(@project,notification),:class=>'btn btn-mini') unless notification.response 
	    msg.html_safe
	  end
	end
end

app/views/notifications/_form.html.erb
<%=render 'common/css'%>
<link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css">
<%
  if @notification.new_record?
    @url = project_notifications_path(@project)
  else
    @url = project_notification_path(@project,@notification)
  end
%>
<%= simple_form_for @notification, :url => @url, :html => { :class => 'form-horizontal' } do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group ">
    <%= f.label :student_id, :class => ' control-label' %>
    <div class="controls">
      <%= f.collection_select :person_id, Student.all, :id, :username,{},{:multiple=>true,:class=>'span2'} %>
    </div>
  </div>

  <%= f.input :title %>
  <%= f.input :state,:collection=>['无需确认通知','需确认通知'] %>
  <%= f.input :content,:input_html=>{:rows=>5} %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                project_notifications_path(@project), :class => 'btn' %>
  </div>
<% end %>

<script>
  $(function(){
    $("#notification_person_id").val(gon.students_id).select2({
      placeholder: "请选择学员",
    })
    // $("#notification_person_id").
    $('#notification_content').summernote({
      lang: 'zh-CN',
      toolbar: [
        ['insert', ['link']], // no insert buttons
      ]
    });
    
  })
</script>
<style>
.modal-backdrop{display: none!important}
.note-editor{width:400px;}
.icon-link{background-position: 0,0}
</style>

app/views/notifications/_table.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>标题</th>
      <!-- <th>资源</th> -->
      <th>类型</th>
      <th>接收人</th>
      <th>通知时间</th>
      <th>状态</th>
      <th>确认来源</th>
    </tr>
  </thead>
  <tbody>
    <% collection.each do |notification| %>
      <tr>
        <td><%= link_to notification.title, project_notification_path(@project,notification) %></td>
<!--         <td>
          <% if notification.notificatable.is_a? Klassplan  %>
          <%= link_to notification.notificatable.id, project_klassplan_path(@project,notification.notificatable)%>
          <% end %>
        </td> -->
        <td><%= notification.state_zh %></td>
        <td><%= notification.person.try(:username) %></td>
        <td><%= notification.notify_at.to_formatted_s(:db) %></td>
        <td>
          <%=response_msg(notification)%>
        </td>
        <td><%= notification.laiyuan%></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

app/views/notifications/index.html.erb
<%=render 'common/css'%>
<h1>通知列表</h1>

<%=render 'notifications/table',:collection=>@notifications %>

<%= paginate @notifications %>

<%= link_to '创建通知',
            new_project_notification_path(@project),
            :class => 'btn' %>

app/views/notifications/new.html.erb
<div class="page-header">
  <h1>创建通知</h1>
</div>

<%= render 'form' %>

app/views/notifications/show.html.erb
<%=render 'common/css'%>
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered">
<tr>
	<td>
  	<b>标题:</b>
	</td>
  <td><%= @notification.title %></td>
</tr>

<tr>
	<td>
  	<b>通知类型:</b>
	</td>
  <td><%= t @notification.state %></td>
</tr>

<tr>
	<td>
  	<b>通知时间:</b>
	</td>
  <td><%= @notification.notify_at %></td>
</tr>

<tr>
	<td>
  	<b>收件人:</b>
	</td>
  <td><%= @notification.person.try(:username) %></td>
</tr>

<tr>
	<td>
  	<b>内容:</b>
	</td>
  <td><%= @notification.content.html_safe %></td>
</tr>
</table>
<%= link_to '通知列表', project_notifications_path(@project),:class=>'btn' %>