config/routes.rb
  mount WillFilter::Engine => "/will_filter"

  resources :attaches,:except=>[:show] do 
  end

  resources :klassplanitems do 
    member do 
      post 'set_finished'
    end
  end

  get 'entrance/:id/finish_baoming_kpi'=>"entrance#finish_baoming_kpi",:as=>"entrance_finish_baoming_kpi"
  get 'reviews/search_by_phone'
  
  get "entrance/index"

  get "entrance/resources"

  match "reviews/prepare"=>"reviews#prepare",:as=>"prepare_review"

  root :to => "entrance#index"

  post "api/login"

  post "api/logout"

  post "api/notifications"

  post "api/notification"

  post "api/notificate"  

  post 'api/feedback'

  resources :markets do 
    resources :clients do
    end
  end

  resources :students do 
    resources :achieves do
      member do
        match :finish
        match :unfinish
      end
    end
  end

  resources :baomings_klassplanitems do
    member do
      match :plan
      match :wait_confirm
      match :confirm
      match :request_leave
      match :leave
      match :finish
      match :uncomplete
    end
  end
  resources :projects do

    resources :achieves

    resources :feedbacks

    resources :stats

    resources :entrance do
      collection do
        match 'index'
        match 'feedbacks'
      end
    end

    resources :notification_templates

    resources :seasons do 
      member do
        match :set_now
      end
    end

    

    resources :rules

    resources :baomings,:except=>[:new,:create] do
      member do
        match :pay
      end
    end

  	resources :markets

    resources :courses

    resources :services

  	resources :rooms do
      collection do
        match 'filter_rooms'
      end
      member do
        match 'duplicate'
      end
    end

  	resources :teachers do
      member do
        match 'duplicate'
      end
    end

  	resources :students do
      member do
        match 'duplicate'
        match 'to_client'
        match 'to_student'
        match 'to_alumna'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :clients do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :alumnas do
      member do
        match 'duplicate'
      end

      collection do
        delete 'destroy_multiple'
      end
    end

    resources :notifications do
      member do 
        match 'confirm'
        match 'unconfirm'
      end
    end

    resources :klassplans do
      member do 
        match 'start_plan'
        match 'confirm_plan'
        match 'ajax_menu'
        match 'ajax_kpis'
        match 'ajax_teachers'
        match 'ajax_rooms'
        match 'ajax_resources'
        match 'ajax_baoming'
        match 'wait_teacher_confirm'
      end

      collection do
        match 'planed_calendar'
        match 'planing_calendar'
        match 'autoplaning_calendar'
        match 'finished_calendar'
        match 'all_calendar'
        match 'auto'
        match 'start_auto'
        match 'dashborad'
      end
    end

    resources :reviews do
      member do
        match 'start'
        match 'set_feedbacked'
      end
      collection do
        get 'all'
        get 'my'
        get 'my_finished'
        get 'my_unfinished'
        get 'my_payed'
        match 'search_by_phone'
        match 'chose_reviewers'
        match 'available_reviewers'
      end
    end
  end

  resources :services

  resources :scores

  resources :warnings

  resources :people

  resources :students do
    resources :reviews
  end

  resources :teachers

  match ':controller(/:action(/:id))(.:format)'

app/models/notification_template.rb
class NotificationTemplate < ActiveRecord::Base
	attr_accessible :title,:content

	State = [:teacher_confirm,:student_confirm,:plan_klass_success,:before_klass,:after_klass]
end

app/controllers/notification_templates_controller.rb
class NotificationTemplatesController < ApplicationController
  NotificationTemplate
  before_filter :find_project, :authorize          
  # GET /notification_templates
  # GET /notification_templates.json
  def index
    @notification_templates = NotificationTemplate.order('created_at desc')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @notification_templates }
    end
  end

  # GET /notification_templates/1
  # GET /notification_templates/1.json
  def show
    @notification_template = NotificationTemplate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @notification_template }
    end
  end

  # GET /notification_templates/new
  # GET /notification_templates/new.json
  def new
    @notification_template = NotificationTemplate.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @notification_template }
    end
  end

  # GET /notification_templates/1/edit
  def edit
    @notification_template = NotificationTemplate.find(params[:id])
  end

  # POST /notification_templates
  # POST /notification_templates.json
  def create
    @notification_template = NotificationTemplate.new(params[:notification_template])

    respond_to do |format|
      if @notification_template.save
        format.html { redirect_to @notification_template, notice: 'Notification template was successfully created.' }
        format.json { render json: @notification_template, status: :created, location: @notification_template }
      else
        format.html { render action: "new" }
        format.json { render json: @notification_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /notification_templates/1
  # PUT /notification_templates/1.json
  def update
    @notification_template = NotificationTemplate.find(params[:id])

    respond_to do |format|
      if @notification_template.update_attributes(params[:notification_template])
        format.html { redirect_to @notification_template, notice: 'Notification template was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @notification_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notification_templates/1
  # DELETE /notification_templates/1.json
  def destroy
    @notification_template = NotificationTemplate.find(params[:id])
    @notification_template.destroy

    respond_to do |format|
      format.html { redirect_to notification_templates_url }
      format.json { head :no_content }
    end
  end
  private 

  def find_project
    # p params
    @project = Project.find_by_identifier(params[:project_id])
    # p @project
  end            
end

app/helpers/notification_templates_helper.rb
module NotificationTemplatesHelper
end

app/views/notification_templates/_form.html.erb
<%= form_for(@notification_template) do |f| %>
  <% if @notification_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification_template.errors.count, "error") %> prohibited this notification_template from being saved:</h2>

      <ul>
      <% @notification_template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br />
    <%= f.number_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notification_templates/edit.html.erb
<h1>Editing notification_template</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification_template %> |
<%= link_to 'Back', notification_templates_path %>

app/views/notification_templates/index.html.erb
<h1>Listing notification_templates</h1>

<table>
  <tr>
    <th>State</th>
    <th>Title</th>
    <th>Content</th>
    <th>Project</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @notification_templates.each do |notification_template| %>
  <tr>
    <td><%= notification_template.state %></td>
    <td><%= notification_template.title %></td>
    <td><%= notification_template.content %></td>
    <td><%= notification_template.project_id %></td>
    <td><%= link_to 'Show', notification_template %></td>
    <td><%= link_to 'Edit', edit_notification_template_path(notification_template) %></td>
    <td><%= link_to 'Destroy', notification_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Notification template', new_notification_template_path %>

app/views/notification_templates/new.html.erb
<h1>New notification_template</h1>

<%= render 'form' %>

<%= link_to 'Back', notification_templates_path %>

app/views/notification_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
  <%= @notification_template.state %>
</p>

<p>
  <b>Title:</b>
  <%= @notification_template.title %>
</p>

<p>
  <b>Content:</b>
  <%= @notification_template.content %>
</p>

<p>
  <b>Project:</b>
  <%= @notification_template.project_id %>
</p>


<%= link_to 'Edit', edit_notification_template_path(@notification_template) %> |
<%= link_to 'Back', notification_templates_path %>